version: '3.3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
#    networks:
#        - kafka-network

  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
#    networks:
#        - kafka-network


#  ai-service:
#    image: rajsubhod/ai-service
#    depends_on:
#      - kafka
#      - zookeeper
#    environment:
#      LLM_KEY: "EsM5DG0Z7Cg8cu73hYk1zAQpZKcdPLlA"
#      PORT: 9040
#      HOST: 0.0.0.0
#      KAFKA_BOOTSTRAP_SERVERS: kafka
#      KAFKA_BOOTSTRAP_PORT: 9092
#      KAFKA_BROKER_ID: 2
#      KAFKA_TOPIC_NAME: transaction