# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

POST http://127.0.0.1:5000/api/v1/message
Content-Type: application/json

{
    "message": "INR 294.99 spent on ICICI Bank Card XX7003 on 23-Apr-24 at TW Coffee Kora. Avl Lmt: INR 43,266.15. To dispute,call 18002662/SMS BLOCK 7003 to 9215676766",
    "name": "John Doe"
}

###


Content-Type: application/json

{
    "message": "INR 1000 debited Ac/XX1234 and credited to EKART via UPI Ref No 123456789 on 1Sep24. Call 11111111 if not done by you. -BOI",
    "name": "Alen Jones"
}

###

POST http://127.0.0.1:9040/api/v1/message
Content-Type: application/json

{
    "message": "'BOI -  Rs.900.00 Credited to your Ac XXX1111 on 02-12-04 by UPI ref No.2324.Avl Bal 3988.23'",
    "name": "Alen Jones"
}